#!/usr/bin/env bash
# A script that uses cass for complex conditionals

n=0

while [ $((n++)) -lt 20 ]; do
        echo $n
	case $n in 4)
	        echo bad luck from China
		;;
	9)
	        echo bad luck from Japan
		;;
	17)
	        echo bad luck from Italy
		;;
	esac
done
